### ISSUE TITLE
Will you provide CAE's training logs?

### ISSUE THREAD

**Issue by bsxxdw** [lxtGH/CAE#1]
I'm planing to train CAE with ImageNet1K dataset. But it takes about 1 hour to train CAE with one epoch, which is much longer than MAE (about 4 minutes per epoch). Is it normal? How long did you take to train CAE for 800 epochs?

**Comment by SelfSup-MIM** [comment]
Hi, it takes about 6.5 minutes (batch size = 2048) to train CAE-base for one epoch on 32 V100 GPUs.
Training logs will be uploaded soon.

**Comment by bsxxdw** [comment]
Thanks for your reply, and your great work!

**Comment by SelfSup-MIM** [comment]
@bsxxdw Training logs of base models are available: https://drive.google.com/drive/folders/1wwhg7nj2GQuU9uthVuQLkEEXEjx90G7g?usp=sharing.

**Comment by 1024er** [comment]
> @bsxxdw Training logs of base models are available: https://drive.google.com/drive/folders/1wwhg7nj2GQuU9uthVuQLkEEXEjx90G7g?usp=sharing.

This link is unavailable now
