### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ross-Hr** [lxtGH/CAE#2]
Hi, i just two suggestions when i run your CAE:
(i)
Your data dir is ' data_root = '/root/paddlejob/workspace/env_run//' '.
So there could be some unknown attacks.

(ii)
Your structure of  'downstream_task/detection/evaluation/object_detection' is awful, so that i  run the code directly in my server and get an import BUG .

**Comment by SelfSup-MIM** [comment]
Thanks for your reminder! We have fix (i). Could you provide more details of issue (ii)?

**Comment by ross-Hr** [comment]
> Thanks for your reminder! We have fix (i). Could you provide more details of issue (ii)?

In  the directory :  .../downstream_tasks/detection/evaluation/object_detection :

I create a.sh or b.sh in `detection/evaluation/object_detection`  for training. It seems like :
....
python -m torch.distributed.launch --nproc_per_node=2 \
....

I also move the library `detection/models` into `mmcv_custom/models`.

**Comment by SelfSup-MIM** [comment]
There is no need to move `models` to `mmcv_custom`. We follow ibot to run object detection experiments.
Please enter `downstream_tasks/detection/` and run your scripts in this folder.

**Comment by ross-Hr** [comment]
.
|-- __init__.py
|-- a.sh
|-- a.txt
|-- b.sh
|-- configs
|   |-- _base_
|   |   |-- datasets
|   |   |    -- coco_instance.py
|   |   |-- default_runtime.py
|   |   |-- models
|   |   |   |-- cascade_mask_rcnn_r50_fpn.py
|   |   |   |-- cascade_mask_rcnn_swin_fpn.py
|   |   |   |-- cascade_mask_rcnn_vit_fpn.py
|   |   |   |-- mask_rcnn_r50_fpn.py
|   |   |    -- mask_rcnn_vit_fpn.py
|   |    -- schedules
|   |        -- schedule_1x.py
|    -- mask_rcnn
|       |-- vit_base_giou_4conv1f_coco_maskrcnn_1x_cae_sincos_init0.1_lr00003.py
|        -- vit_large_giou_4conv1f_coco_maskrcnn_1x_cae_sincos_init0.1_lr00002_lrdr0.85_dp0.2.py
|-- mmcv_custom
|   |-- __init__.py
|   |-- __pycache__
|   |   |-- __init__.cpython-36.pyc
|   |   |-- checkpoint.cpython-36.pyc
|   |   |-- layer_decay_optimizer_constructor.cpython-36.pyc
|   |   |-- prepare_rpe.cpython-36.pyc
|   |   |-- register_backbone.cpython-36.pyc
|   |    -- utils.cpython-36.pyc
|   |-- checkpoint.py
|   |-- layer_decay_optimizer_constructor.py
|   |-- loader.py
|   |-- models
|   |   |-- __init__.py
|   |   |-- __pycache__
|   |   |   |-- __init__.cpython-36.pyc
|   |   |   |-- swin_transformer.cpython-36.pyc
|   |   |    -- vision_transformer.cpython-36.pyc
|   |   |-- head.py
|   |   |-- swin_transformer.py
|   |    -- vision_transformer.py
|   |-- prepare_rpe.py
|   |-- register_backbone.py
|   |-- runner
|   |   |-- __init__.py
|   |   |-- __pycache__
|   |   |   |-- __init__.cpython-36.pyc
|   |   |   |-- checkpoint.cpython-36.pyc
|   |   |    -- epoch_based_runner.cpython-36.pyc
|   |   |-- checkpoint.py
|   |    -- epoch_based_runner.py
|    -- utils.py
|-- output_dir
|   |-- 20220630_151058.log
|   |-- 20220630_151058.log.json
|   |-- epoch_1.pth
|   |-- epoch_2.pth
|   |-- latest.pth -> epoch_2.pth
|    -- vit_base_giou_4conv1f_coco_maskrcnn_1x_cae_sincos_init0.1_lr00003.py
|-- test.py
 -- train.py

13 directories, 48 files

**Comment by ssocean** [comment]
add code below to the very first of the script could be more than enough~
import sys
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)
