### ISSUE TITLE
torch.distributed.elastic.multiprocessiong.erroes.ChildFailedError:

### ISSUE THREAD

**Issue by linglingl635** [lxtGH/CAE#7]
why my terminal tell me this problem after training epoch 0?
how can I fix it?
![47O$WG{BIG$~(TH4LZECK_I](https://user-images.githubusercontent.com/97529018/195495646-e355fc79-3ef1-4925-9712-fd7f86ed3481.png)

**Comment by SelfSup-MIM** [comment]
Hi, we haven't met this problem before and I guess it has nothing to do with the code. 
Are the environment installed exactly the same as the readme file?
